### ISSUE TITLE
declad also cannot create a dataset due to a permissions problem

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#468]
This is a very similar code path and we are hitting the same error that Justin-rucio-upload is hitting
namely
Mover failed: np02vdcoldbox_raw_run023744_0251_dataflow0_datawriter_0_20240115T032112.hdf5 status: quarantined error: Error in creating Rucio dataset vd-coldbox:vd-coldbox_23744: Access to the requested resource denied.
Details: Account dunepro can not add data identifier to scope vd-coldbox

So as with Justin-rucio-upload it is failing as it is trying to create the dataset.
Fixing this problem with the permissions package is now paramount.
all our data will get quarantined until we do.

**Comment by jamesp-epcc** [comment]
Hi Steve, apologies for not getting back to you sooner, I am off work ill just now and haven't been on my email much.

I think this is related to the new checks which ensure datasets and container (not just files) exist in MetaCat before they are added to Rucio. If the datasets that are failing are not present in MetaCat then this error is expected behaviour. Otherwise it sounds like a bug.

I can investigate this properly when I am back at work, but if you need a quick fix, deleting the if statement from `perm_add_did` that calls `_dataset_exists` should allow you to add data again.

**Comment by StevenCTimm** [comment]
I will have to document this a bit better, but it appears that the call to create the dataset is failing even when the dataset is already present in metacat, and even if it already exists.  

I guess I am a bit puzzled because the permission.py code itself doesn't make any reference to metacat at all, it looks
like it will fail regardless whether the dataset is in metacat or not.

can you please give us a pointer to what the 1.29 version of permission.py used to look like so I can see what changed.


And thanks for the suggestion about commenting out those checks.. the idea had also occurred to me although 
I don't have Brandon available right now, he's also out, so it might take a while.

Hope you get better soon and let us know when you're back at it and we will talk some more at that time.

**Comment by jamesp-epcc** [comment]
The call to MetaCat is within the `_dataset_exists` function above `perm_add_did`. If it's returning false for datasets that do exist in MetaCat then that sounds like a bug that needs to be investigated.

This is `permission.py` as it was before I added the dataset check: https://github.com/jamesp-epcc/DUNERucioPolicy/blob/18a2951d9ef43292919332f64ec3ec03054af0a5/permission.py

**Comment by StevenCTimm** [comment]
See issue #467 to see the debugging output that I did to test the various test cases.

**Comment by jamesp-epcc** [comment]
Hi Steve, I am back from sick leave today. I see the corresponding Justin issue has now been closed after the problem was traced to a default account being used. Is that also the case for this issue or is there still an outstanding bug here?

**Comment by StevenCTimm** [comment]
Here in the declad we are using the correct account.  What has to happen is that a patch needs to be made to the declad such that it will declare the internal dataset in metacat, which it hasn't been doing up until now.  (the late author of Metacat didn't want to do it this way, but now we have to).  I have changed the tags on the ticket such that it is a declad issue now and not a rucio bug, and will take the assignment myself.

**Comment by jamesp-epcc** [comment]
It's an internal Rucio data type. Since the multi VO work, most objects are represented inside the Rucio core by an ID which isn't very meaningful outside Rucio (to avoid name clashes between different VOs). So to get the external representation that's actually meaningful (in this case the scope's name) you have to use the `.external` property.

**Comment by StevenCTimm** [comment]
Marc has given me a patch for the declad, which works.. it is currently installed on protodune-declad-np04
and I am cleaning up the large backlog of quarantined files.

**Comment by StevenCTimm** [comment]
Another minor patch was required to handle the case when the metacat dataset already existed, this has now been done.

Will now propagate these patches to the protodune-declad-np02 machine and then coordinate with Doug on the Fermilab side.

**Comment by StevenCTimm** [comment]
DONE!
