### ISSUE TITLE
request for rule to move hist files to persistent

### ISSUE THREAD

**Issue by hschellman** [DUNE/data-mgmt-ops#666]
Once we get the root-tuple-virtual, I can provide a query that will ask for the files to go to fnal for merging.  I will update this request when that is available.

**Comment by hschellman** [comment]
Ok, here is the metacat query.  I don't know how this translates into a rucio rule. Can you maybe describe it a bit when you respond to this ticket? Thanks, Heidi 

I can make a dataset if that helps.  Not certain how one updates it though as files come in. 

metacat query "files where created_timestamp > 2024-07-01 and core.data_tier=root-tuple-virtual and core.file_type=detector and core.run_type=hd-protodune"

**Comment by hschellman** [comment]
Actually - let's be more specific 

metacat query "files where created_timestamp > 2024-07-01 and core.data_tier=root-tuple-virtual and core.file_type=detector and core.run_type=hd-protodune and dune.campaign=hd-protodune-reco-keepup-v0"

**Comment by dougbenjamin** [comment]
Hi Heidi,

It is best to move datasets. A metacat query like the one you showed now means I have to go through all the files, identify their parent datasets and then create the rules associated with the parent datasets.
I will look at it in the morning.

Regards,
Doug

From: Heidi Schellman ***@***.***>
Date: Tuesday, July 2, 2024 at 9:10 PM
To: DUNE/data-mgmt-ops ***@***.***>
Cc: Doug Benjamin ***@***.***>, Assign ***@***.***>
Subject: Re: [DUNE/data-mgmt-ops] request for rule to move hist files to persistent (Issue #666)

Actually - let's be more specific

metacat query "files where created_timestamp > 2024-07-01 and core.data_tier=root-tuple-virtual and core.file_type=detector and core.run_type=hd-protodune and dune.campaign=hd-protodune-reco-keepup-v0"

**Comment by hschellman** [comment]
I can make a metacat dataset - one question is how we grow them as new files come in?

and how would I convey that information to you?  We don’t want all the output from those jobs, just the hist files and I think they are likely comingled at the moment.

So our first request should be that files that need to be merged need to go into their own dataset - datasets need to be granular at the data_tier level to avoid comingling stuff.





On Jul 2, 2024, at 8:40 PM, Doug Benjamin ***@***.***> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]

Hi Heidi,

It is best to move datasets. A metacat query like the one you showed now means I have to go through all the files, identify their parent datasets and then create the rules associated with the parent datasets.
I will look at it in the morning.

Regards,
Doug

From: Heidi Schellman ***@***.***>
Date: Tuesday, July 2, 2024 at 9:10 PM
To: DUNE/data-mgmt-ops ***@***.***>
Cc: Doug Benjamin ***@***.***>, Assign ***@***.***>
Subject: Re: [DUNE/data-mgmt-ops] request for rule to move hist files to persistent (Issue #666)

Actually - let's be more specific

metacat query "files where created_timestamp > 2024-07-01 and core.data_tier=root-tuple-virtual and core.file_type=detector and core.run_type=hd-protodune and dune.campaign=hd-protodune-reco-keepup-v0"

**Comment by hschellman** [comment]
I have found 2 datasets in metacat which seem to correspond to rucio scopes.  

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2382
hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2381

It would be good to get metadata added to datasets so these were easier to find.  I found these by brute force checking all of the files that matched the query to make certain I missed none.   All one needs to do is add a tag to the dataset metadata that says thing like - hey mergeme!

These are still root-tuple - no non-trivial files created since Jake changed to virtual data_tier.

**Comment by StevenCTimm** [comment]
The right way to do this would have been to query Justin on the produced workflows and that would have told you what the dataset names were in metacat and rucio.

**Comment by hschellman** [comment]
For this kind of merging the best thing to do is to produce input datasets (and presumably workflows) based on run numbers or run number ranges.

Merging is best done run-by-run and it is very satisfying to see real runs being processed. I have made a program which pulls out the summary data which is useful here.

Here is example info, our goal should be to have the counts for raw and reconstructed match.
I am not filtering out duplicates which is why I found so many.

run     data_stream     raw:count       raw:total_size_gb       full-reconstructed:count        full-reconstructed:total_size_gb
27425   cosmics 11084   46954.319
27279   cosmics 5516    23308.934       2474    1859.544
27388   physics 4664    19744.797
27309   physics 4584    19380.002       14326   14238.183
27331   physics 4144    17553.648       3785    4485.551
27105   cosmics 3556    15179.986
27394   physics 3084    13061.754
27310   physics 3033    12819.321       8451    8682.037


On Jul 5, 2024, at 12:22 PM, Steven Timm ***@***.***> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


The right way to do this would have been to query Justin on the produced workflows and that would have told you what the dataset names were in metacat and rucio.

**Comment by StevenCTimm** [comment]
Heidi added this in E-mail:

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2370

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2371

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2372

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2373

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2377

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2381

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2382



Here is what I have found for datasets that have files that should be merged.  Doug can you please set up the rules to move to FNAL space?   I would prioritize 2382 and 2381 as those are the latest.



Not certain where the files from later runs are as 2382 is the highest here.

**Comment by dougbenjamin** [comment]
Hello,

I will do it later this morning.

Doug

From: Steven Timm ***@***.***>
Date: Tuesday, July 9, 2024 at 10:48 AM
To: DUNE/data-mgmt-ops ***@***.***>
Cc: Doug Benjamin ***@***.***>, Assign ***@***.***>
Subject: Re: [DUNE/data-mgmt-ops] request for rule to move hist files to persistent (Issue #666)

Heidi added this in E-mail:

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2370

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2371

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2372

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2373

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2377

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2381

hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2382

Here is what I have found for datasets that have files that should be merged. Doug can you please set up the rules to move to FNAL space? I would prioritize 2382 and 2381 as those are the latest.

Not certain where the files from later runs are as 2382 is the highest here.

**Comment by StevenCTimm** [comment]
Already done.. Steve

________________________________

**Comment by StevenCTimm** [comment]
I added the rules as follows:

[dunepro@duneopsgpvm01 dunepro]$ rucio add-rule --account=dunepro  hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2370 1 DUNE_US_FNAL_DISK_STAGE
f82b594bb6b54798912af18b54bfd298
[dunepro@duneopsgpvm01 dunepro]$ rucio add-rule --account=dunepro  hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2371 1 DUNE_US_FNAL_DISK_STAGE
0657975f32b9458dabb3979053971a0f
[dunepro@duneopsgpvm01 dunepro]$ rucio add-rule --account=dunepro  hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2372 1 DUNE_US_FNAL_DISK_STAGE
2b21847b29894059bbea9c4b019cd638
[dunepro@duneopsgpvm01 dunepro]$ rucio add-rule --account=dunepro  hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2373 1 DUNE_US_FNAL_DISK_STAGE
2046cc2021404fd4afc14237f71ad15e
[dunepro@duneopsgpvm01 dunepro]$ rucio add-rule --account=dunepro  hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2377 1 DUNE_US_FNAL_DISK_STAGE
cb8544ee1fdd4af9b6f4919623620260
[dunepro@duneopsgpvm01 dunepro]$ rucio add-rule --account=dunepro  hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2381 1 DUNE_US_FNAL_DISK_STAGE


got all but 2382 done then all hell broke loose and rucio became completely unresponsive, investigating.

**Comment by StevenCTimm** [comment]
2382 must have been done by Doug because when I went to make it it was already there.

This is status of these rules at the moment:

[dunepro@duneopsgpvm01 dunepro]$ rucio list-rules --account=dunepro | grep hd-protodune-det-reco:calcuttj_keepup_cal_cal_
1fcdbbea7b044b649789a19ebe504a88  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2382                                                                                     OK[10082/0/0]             DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-06-22 11:59:08
119c31bfb1b34dfd9c795f9202c6e29e  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2381                                                                                     REPLICATING[22745/805/0]  DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-07-09 15:46:31
0657975f32b9458dabb3979053971a0f  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2371                                                                                     REPLICATING[9/1/0]        DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-07-09 15:46:04
2046cc2021404fd4afc14237f71ad15e  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2373                                                                                     REPLICATING[6/4/0]        DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-07-09 15:46:15
2b21847b29894059bbea9c4b019cd638  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2372                                                                                     OK[10/0/0]                DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-07-09 15:46:09
cb8544ee1fdd4af9b6f4919623620260  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2377                                                                                     REPLICATING[78/33/0]      DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-07-09 15:46:23
f82b594bb6b54798912af18b54bfd298  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2370                                                                                     OK[108/0/0]               DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-07-09 15:45:57

**Comment by StevenCTimm** [comment]
There are a few files from the older workflows that are at QMUL and we won't get those off because it is down until September. Most of the rest of them are now at Fermilab.

Steve Timm
***@***.*** dunepro]$ rucio list-rules --account=dunepro | grep hd-protodune-det-reco:calcuttj_keepup_cal_cal_
1fcdbbea7b044b649789a19ebe504a88  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2382                                                                                     OK[10082/0/0]             DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-06-22 11:59:08
119c31bfb1b34dfd9c795f9202c6e29e  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2381                                                                                     REPLICATING[22745/805/0]  DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-07-09 15:46:31
0657975f32b9458dabb3979053971a0f  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2371                                                                                     REPLICATING[9/1/0]        DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-07-09 15:46:04
2046cc2021404fd4afc14237f71ad15e  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2373                                                                                     REPLICATING[6/4/0]        DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-07-09 15:46:15
2b21847b29894059bbea9c4b019cd638  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2372                                                                                     OK[10/0/0]                DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-07-09 15:46:09
cb8544ee1fdd4af9b6f4919623620260  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2377                                                                                     REPLICATING[78/33/0]      DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-07-09 15:46:23
f82b594bb6b54798912af18b54bfd298  dunepro    hd-protodune-det-reco:calcuttj_keepup_cal_cal_062024_ntuple_2370                                                                                     OK[108/0/0]               DUNE_US_FNAL_DISK_STAGE  1         N/A                              2024-07-09 15:45:57
________________________________

**Comment by StevenCTimm** [comment]
We are making this rule now for all new datasets coming out of keep-up processing.
The rules above it turned out were for datasets which have to be deleted because they were no good and the files are at Fermilab now but will have to be deleted shortly.
