### ISSUE TITLE
Ask providers who haven't enabled httpd as copy mechanism to please do so.

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#72]

**Comment by StevenCTimm** [comment]
Need to find all the httpd/webdav urls of the various sites and test copies by hand first, then add them one by 
one to rucio.. there's no way to prestage files with httpd/webdav either so the prestaging becomes important here.

**Comment by wyuan-uoe** [comment]
I can find most of the httpd/webdav urls in GOCDB. I'll test them one by one and contact the provider if the url is not available for DUNE.

**Comment by wyuan-uoe** [comment]
I tested all the sites which are not enabled httpd/webdav, with the following tests:

1. `gfal-copy` https urls upload/download with the sites

2. `fts-transfer-submit` transfers between the sites and FNAL_DCACHE_TEST using https urls

3. `Rucio upload/download` locally on the sites

4. `Rucio add rule` to transfers replicas between the sites and FNAL_DCACHE_TEST

I've add the https urls to Rucio RSEs. Now LANCASTER, MANCHESTER, RAL-PP, LIVERPOOL, IMPERIAL work fine. 

CERN_PDUNE_EOS cannot write in Rucio because `availability_write: False` setting in Rucio. However, `Rucio download` works for CERN_PDUNE_EOS, while add rule copying replica to CERN_PDUNE_EOS, it shows an error "NO_SOURCES:NO_SOURCES", as ruleid 875679fbcaa34962bbde54b9885c22a1.

QMUL and RAL_ECHO still not work. QMUL has a GGUS ticket for the accessing problem. RAL_ECHO are waiting for an update of XrootD for the further test.

**Comment by StevenCTimm** [comment]
rachid.lemrani@cc.in2p3.fr is the contact at DUNE_FR_CCIN2P3_XROOTD
Have E-mailed him about this.

**Comment by wyuan-uoe** [comment]
https on QMUL works now. 

For RAL_ECHO, `https://xrootd.echo.stfc.ac.uk:1094/dune:/protodune/RSE/` can work other than dynafed.stfc.ac.uk.

**Comment by StevenCTimm** [comment]
https on ccxroot.in2p3.fr works now.
T3_US_NERSC still out there.

Planning to enable https 3rd party copy on FNAL_DCACHE (for outbound) shortly.

**Comment by StevenCTimm** [comment]
This is now closed.
